### ISSUE TITLE
How to verify and decode multiple tokens ?

### ISSUE THREAD

**Issue by hollowshiroyuki** [OpenIDC/mod_oauth2#50]
I'm using Amazon Cognito IdP and the authentication is taken care of by an Amazon Application Load Balancer and the Amazon Hosted UI.

We receive 2 tokens on Apache side : `X-Amnz-Oidc-Accesstoken` on which I base my authorization process as per the [documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-access-token.html), and `X-Amnz-Oidc-Data` which contains some identification data such as the user email address. They're both signed JWTs and can be verified with the same public key.

Is there a way to decode and extract both tokens data ?

Thanks for your assistance :wave:

**Comment by zandbelt** [comment]
firstly I'd say that you should need to do only one of those because it would/should render the same data; If for some reason you'd still need to consume both, the only solution is to configure token verification of one token on a specific path and then proxy internally to a different path that verifies the second token

**Comment by hollowshiroyuki** [comment]
Indeed there's common data in both tokens but some fields are only present in either. Such as the email since it's not required for authorization.

>you should need to do only one of those

Is there a specific reason or is it a best practice ?

**Comment by zandbelt** [comment]
> Indeed there's common data in both tokens but some fields are only present in either. Such as the email since it's not required for authorization.
> 
> > you should need to do only one of those
> 
> Is there a specific reason or is it a best practice ?

it is just that I see no reason: if you're going to include identity data in the access token anyway, leaving out the email address seems arbitrary
