### ISSUE TITLE
How to set a password for redis caching?

### ISSUE THREAD

**Issue by webermax** [OpenIDC/mod_oauth2#52]
We tried the following apache config to get rid of [oauth2:warn] "no crypto passphrase configured":

`OAuth2Cache redis host=localhost&encrypt=false`

But it has no result and the format for the options is not clear (https://github.com/OpenIDC/mod_oauth2/blob/master/oauth2.conf)?

**Comment by zandbelt** [comment]
you can use `OAuth2CryptoPassphrase <string>` which is indeed not correctly documented; I'll change that, thanks
